<?php

namespace Database\Seeders;

use App\Models\Souvenir;
use App\Models\User;
use Illuminate\Database\Seeder;

class SouvenirRealSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = User::where('role', 'admin')->first()?->user_id;

        $souvenirs = [
            [
                'nama_souvenir' => 'Balon Renang Anak',
                'harga' => 50000,
                'stok' => 21,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/balon-renang-anak-50k.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Handbag Tropis Zipper',
                'harga' => 45000,
                'stok' => 51,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/handbag-tropis-zipper-45.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Mini Tote Bag Motif Daun Brown',
                'harga' => 45000,
                'stok' => 53,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/mini-tote-bag-motif-daun-brown-45.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Oversized Tote (Motif Daun Tropis & Kantong Serat)',
                'harga' => 75000,
                'stok' => 30,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/oversized-tote-(motif-daun-tropis-kantong-serat)-75.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Setelan Anak',
                'harga' => 50000,
                'stok' => 47,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/setelan-anak-50k.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Setelan Anak',
                'harga' => 50000,
                'stok' => 32,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/setelan-anak-50k-(2).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Shoulder Bag Kombinasi (Houndstooth & Serat Alam Dengan Aksen Tassel)',
                'harga' => 65000,
                'stok' => 29,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/shoulder-bag-kombinasi-(houndstooth-serat-alam-dengan-aksen-tassel)-65.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Tas Bahu Asimetris',
                'harga' => 65000,
                'stok' => 24,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/tas-bahu-asimetris-65.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Tas Selempang Kecil (Motif Rajut Cokelat Krem)',
                'harga' => 45000,
                'stok' => 15,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/tas-selempang-kecil-(motif-rajut-cokelat-krem)-45.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Tas Serut Tali',
                'harga' => 55000,
                'stok' => 29,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/tas-serut-tali-55.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Tote Bag Segi Empat (Motif Plaid  Kotak Kotak Klasik)',
                'harga' => 65000,
                'stok' => 39,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/tote-bag-segi-empat-(motif-plaid-kotak-kotak-klasik)-65.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Anak2 Ukuran O Dan S Harga',
                'harga' => 35000,
                'stok' => 51,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/anak2-ukuran-o-dan-s-harga-35.000-beli-3-jadi-100.000.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'As Serut Gagang Rotan',
                'harga' => 55000,
                'stok' => 56,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/as-serut-gagang-rotan-55.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Celana Pendek',
                'harga' => 35000,
                'stok' => 25,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/celana-pendek-35.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Stelan Dan Daster Anak XXL Harga',
                'harga' => 60000,
                'stok' => 54,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/stelan-dan-daster-anak-xxl-harga-60.000-(2).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Stelan Dan Daster Anak XXL Harga',
                'harga' => 60000,
                'stok' => 47,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/stelan-dan-daster-anak-xxl-harga-60.000-(3).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Stelan Dan Daster Anak XXL Harga',
                'harga' => 60000,
                'stok' => 22,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/stelan-dan-daster-anak-xxl-harga-60.000.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Stelan Dewasa Celana Pendek Lengan Pendek',
                'harga' => 75000,
                'stok' => 21,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/stelan-dewasa-celana-pendek-lengan-pendek-75.000.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Stelan Dewasa Lengan Panjang Celana Panjang',
                'harga' => 130000,
                'stok' => 58,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/stelan-dewasa-lengan-panjang-celana-panjang-130.000.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Stelan Dwsa Celana Panjang Lengan Pendek',
                'harga' => 85000,
                'stok' => 45,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/stelan-dwsa-celana-panjang-lengan-pendek-85.000.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran L Stelan Anak Harga',
                'harga' => 45000,
                'stok' => 26,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-l-stelan-anak-harga-45.000-(2).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran L Stelan Anak Harga',
                'harga' => 45000,
                'stok' => 17,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-l-stelan-anak-harga-45.000-(3).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran L Stelan Anak Harga',
                'harga' => 45000,
                'stok' => 30,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-l-stelan-anak-harga-45.000-(4).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran L Stelan Anak Harga',
                'harga' => 45000,
                'stok' => 37,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-l-stelan-anak-harga-45.000-(5).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran L Stelan Anak Harga',
                'harga' => 45000,
                'stok' => 18,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-l-stelan-anak-harga-45.000.jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 44,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(10).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 18,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(2).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 37,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(3).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 31,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(4).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 56,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(5).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 30,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(6).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 18,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(7).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 55,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(8).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 60,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000-(9).jpeg',
                'updated_by' => $adminId,
            ],
            [
                'nama_souvenir' => 'Ukuran M Stelan Anak\' Harga',
                'harga' => 40000,
                'stok' => 38,
                'status' => 'Tersedia',
                'detail' => 'Souvenir cantik khas Harau dan Natasha Souvenir dengan bahan premium pilihan.',
                'foto' => 'storage/souvenirs/ukuran-m-stelan-anak-harga-40.000.jpeg',
                'updated_by' => $adminId,
            ],
        ];

        foreach ($souvenirs as $data) {
            Souvenir::create($data);
        }
    }
}
